### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by anoonan** [lyft/gostats#41]
We are using [lyft's rate limit service](https://github.com/lyft/ratelimit) and would like to flush the stats it produces to a statsd UDP server. It looks like it's using this library for stats and this library only supports TCP so it'd be great if there was support for UDP as well.

**Comment by armsnyder** [comment]
👍 
It would be handy if I could specify UDP so my on-box datadog agent could receive the statsd metrics without need for a custom adapter

**Comment by armsnyder** [comment]
I changed "tcp" to "udp" in the code and it totally worked, so a proper feature implementation would probably require minimal effort. I'm gonna take a stab at a PR.

**Comment by charlievieth** [comment]
UDP support can now be configured via the `DefaultStatsdProtocol` setting:

https://github.com/lyft/gostats/blob/d95cbc015671ba6dfa360b998633121f816281d5/settings.go#L14-L15

**Comment by charlievieth** [comment]
Also, apologies for the delay in responding (I kinda forget to check the issues here). Would love to know if you all end up using gostats with UDP and IMO it should've been UDP from the get-go (but thats spilt milk). Also, theres been some serious performance improvements to `gostats` in the past year - so if you're using this lib I would definitely recommend using `v0.4.1`+ since we've made it stupid fast.
